# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  name: 'Build'
  inputs:
    command: 'build'
  
- task: DotNetCoreCLI@2
  name: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/ProjetoIA.Apresentacao.csproj'
    arguments: '-p:PublishSingleFile=true'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'd:\a\1\s\ProjetoIA.Apresentacao\bin\Debug\netcoreapp3.1\publish\'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Executavel.zip'
    replaceExistingArchive: true

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'Github EGasparotto'
    repositoryName: 'egasparotto/ProjetoIA'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: userSpecifiedTag
    tag: $(Build.BuildNumber)
    isPreRelease: false
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    assets: '$(Build.ArtifactStagingDirectory)/Executavel.zip'