# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  
- task: DotNetCoreCLI@2
  name: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/ProjetoIA.Apresentacao.csproj'
    arguments: '-p:PublishSingleFile=true -r win-x64 -c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --self-contained true'

- task: DotNetCoreCLI@2
  name: 'Publish2'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/ProjetoIA.Console.csproj'
    arguments: '-p:PublishSingleFile=true -r win-x64 -c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --self-contained true'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/ProjetoIA.Apresentacao.zip'
    destinationFolder: '$(Build.ArtifactStagingDirectory)/Saida'
    cleanDestinationFolder: true

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'Github EGasparotto'
    repositoryName: 'egasparotto/ProjetoIA'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: userSpecifiedTag
    tag: $(Build.BuildNumber)
    isPreRelease: false
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
    assets: 
      -'$(Build.ArtifactStagingDirectory)/Saida/ProjetoIA.exe'
      -'$(Build.ArtifactStagingDirectory)/ProjetoIA.Console.exe'